### PR TITLE
Support for CPU thermal zones

### PR DESCRIPTION
**Pull request by bencevarga666**
I read about a few cases where `thermal_zone0` was maybe not the value someone is looking for as multiple thermal zones are exposed. This PR adds support for these zones, which should mean better support for devices other than a Raspberry Pi.

https://www.reddit.com/r/rust/comments/13fgfft/i_got_an_issue_with_the_crate_nixinfo/
https://askubuntu.com/questions/1110943/what-do-the-different-thermal-zones-actually-correspond-to

### CODE REVIEW

**Comment by Phate6660** [comment]
I am so so sorry for the late reply, I was computer-less for a long time but I'm back now!
This looks really good, but one thing irks me.
I specifically return information as a `String`, for ease of use of the library.

`nixinfo` is currently broken on Rust 2021 Edition as I've come to find out, so I need to sort out those errors. Once those are fixed, if you don't mind, I'll modify this PR to return a `String` and merge the pull request.

**Comment by bencevarga666** [comment]
No problem at all. Let me know if I can help with either of those.

**Comment by Phate6660** [comment]
Any help at all would be greatly appreciated!
I have a lot to do with so many projects due to how long was I off here.
Currently I'm in the middle of making a new project, while fixing three other projects on here not even including this one.
And these are just the first few of my projects I've looked at since getting back on here. :disappointed_relieved:

**Comment by Phate6660** [comment]
I believe I have now fixed the lib, now I just have to touch up the PR and it shall be merged.

**Comment by bencevarga666** [comment]
Okay, I just rebased this branch to include your fixes.

The only thing left is determining what should be the solution for returning `String` only as we have a list of temperature values now. The easiest would be probably just return `Vec<String, Error>`, this way the ease of usability would be kept and also have support for multiple thermal zones. The only con is losing the name of the given thermal zone, but I guess that is not really a problem.

**Comment by bencevarga666** [comment]
I can also make this change happen if you agree with my proposed solution.

**Comment by Phate6660** [comment]
What if we returned `Result<Vec<(String, String)>, Error>`?

That way we get a vector, and each element of the vector is a tuple containing the name and temp?

This was a very quick dirty edit to see if I could get it working (not tested but compiles without errors), but how to you feel about it?

```rust
/// Obtain the temp of CPU thermal zones. Outputs to a Result<Vec<(String, String)>>
pub fn temp() -> Result<Vec<(String, String)>, Error> {
    let thermal_path: String = String::from("/sys/class/thermal/");
    let thermal_zone_path: String = format!("{}{}", thermal_path, "/thermal_zone");
    let paths: fs::ReadDir = fs::read_dir(thermal_path).unwrap();
    let mut temp_data = Vec::new();

    for path in paths {
        let path: std::path::PathBuf = path.unwrap().path();
        let path_str: std::borrow::Cow<str> = path.as_path().to_string_lossy().to_owned();
        if path_str.starts_with(thermal_zone_path.as_str()) {
            let name: String = read_to_string(path_str.to_string() + "/type")?
                .trim()
                .to_owned();
            let temp = read_to_string(path_str.to_string() + "/temp")?
                .trim()
                .parse::<f64>()
                .unwrap()
                / 1000.0;
            let returnable_temp = temp.to_string();
            let tuple = (name, returnable_temp);
            temp_data.push(tuple);
        }
    }
    Ok(temp_data)
}
```

**Comment by bencevarga666** [comment]
I think this is a good idea, just pushed the change.

**Comment by Phate6660** [comment]
I apologize for the long wait!
I meant to go over this yesterday but stuff came up :sweat:

Currently, it doesn't pick up any names or temps for me.
It wasn't accounting for any numbers after `thermal_zone`.

I ended up modifying it to:
```rust
/// Obtain the temp of CPU thermal zones. Outputs to a Result<Vec<(String, String)>>
pub fn temp() -> Result<Vec<(String, String)>, Error> {
    let paths = glob("/sys/class/thermal/thermal_zone*").expect("Failed to read path");
    let mut zone_temps: Vec<(String, String)> = Vec::new();

    for path in paths {
        let path: std::path::PathBuf = path.unwrap();
        let path_str: std::borrow::Cow<str> = path.as_path().to_string_lossy().to_owned();
        let zone_name: String = read_to_string(path_str.to_string() + "/type")?
            .trim()
            .to_owned();
        let temp: f64 = read_to_string(path_str.to_string() + "/temp")?
            .trim()
            .parse::<f64>()
            .unwrap()
            / 1000.0;
        zone_temps.push((zone_name, temp.to_string()));
    }
    Ok(zone_temps)
}
```

Before nothing was output, but when edited I'm now getting the name and temp of hardware (though I only have one on here (`acpitz`), so I'm not sure how well it works for anyone else.

Any thoughts? Testing you wanna do?

**Comment by Phate6660** [comment]
Seems like it's all good now.
I'll merge the PR! 🎉

**Pull request merged**
