### PR TITLE
Add an error type

### PR DESCRIPTION
**Pull request by lnicola**
This doesn't do much for now, but it paves the way towards avoiding a lot of the `unwrap`s that are now present in the code.

And by the way, hello again!

### CODE REVIEW

**Comment by lnicola** [comment]
@Phate6660 gentle ping.

**Comment by Phate6660** [comment]
Sorry, I've been really busy with work and life.
I can't get to this today, but I should be able to tomorrow.

**Comment by lnicola** [comment]
No worries, just making sure you didn't miss it :-).

**Comment by Phate6660** [comment]
Merged. I get out of work in... 7 and a half hours.
When I get out, I'll be looking into this a bit more.

**Pull request merged**
